# Application Name
spring.application.name=task-management

# Server Port
server.port=8080

# Context Path
server.servlet.context-path=/api

# Logging Level
logging.level.root=INFO
logging.level.com.taskapi=DEBUG

# Pretty Print JSON Response
spring.jackson.serialization.indent-output=true
